package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"
	"fmt"
	"go-thorium/graph/model"
)

// InformNonBeliver is the resolver for the informNonBeliver field.
func (r *mutationResolver) InformNonBeliver(ctx context.Context, input model.InformNonBeliverInput) (*model.InformNonBeliverPayload, error) {
	_id++
	fact := r.service.GetThoriumFact(ctx)
	r.service.SendSMS(ctx, input.Phone, fact)
	return &model.InformNonBeliverPayload{
		User: &model.User{
			ID:    fmt.Sprint(_id),
			Phone: input.Phone,
		},
		Message: fact,
	}, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	return &model.User{
		ID:    "1",
		Phone: "+123456789",
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

var _id = 0
